### ISSUE TITLE
Provide JAR file in release, or some way to add this as a dependency

### ISSUE THREAD

**Issue by andrewlalis** [MaeveS2/SnowballNebula#1]
Hello there. I would like to use this library, but at the moment, I am too lazy to clone the repository and compile the source myself. Can you provide a JAR file with your release, or better yet, publish this library on maven central or using jitpack or something?

**Comment by MaeveS2** [comment]
Understandable, i tried to compile to a jar (won't work) and i tried with jitpack which won't work either.

**Comment by danthe1st** [comment]
Alternative possibility: [publish it to GitHub Packages](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry)
